#!/bin/bash
# three domain three switch CR method - verification
# switch distribution 1 , 1 , 1


spin -a three_domain_three_switch_data_test.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_d pan.c
./pan_d
spin -a three_domain_three_switch_ctr_for1.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_c1 pan.c
./pan_c1
spin -a three_domain_three_switch_ctr_for0.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_c0 pan.c
./pan_c0


