#!/bin/bash
# two domain four switch CR three layer - verification
# switch distributions as 3 , 1


ulimit -m 13000000 -v 13000000

spin -a two_domain_four_switch_dist1_data_test_top1.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_d1 pan.c
./pan_d1
spin -a two_domain_four_switch_dist1_data_test_top2.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_d2 pan.c
./pan_d2
spin -a controller_plane_assume_I_3_guarantee_I_1_two_domain_four_switch_dist1.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_c1 pan.c
./pan_c1
spin -a controller_plane_assume_I_3_guarantee_I_2_two_domain_four_switch_dist1.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_c2 pan.c
./pan_c2
spin -a manager_plane_two_domain_gurantee_I_3.pml
gcc -DVECTORSZ=35000 -DCOLLAPSE -o pan_m pan.c
./pan_m



